import { HeaderGlobalSearchParams } from "../components/Header/types";
import { setHeaderOptions } from "./setHeaderOptions";

interface GetHeaderOptionsProps {
    params: HeaderGlobalSearchParams;
};

export function getHeaderOptions({ params }: GetHeaderOptionsProps) {
    const {
        category,
        actorName,
        transparentBackground,
        withBottomStroke,
        withHeaderActions,
        withHeaderLeft,
        withHeaderRight,
        headerRightOptions,
        pointerEvents,
    } = setHeaderOptions({
        signIn: {
            category: '',
            actorName: '',
            transparentBackground: false,
            withBottomStroke: false,
            withHeaderActions: false,
            withHeaderLeft: false,
            withHeaderRight: false,
            headerRightOptions: {
                withFirstAction: false,
                withSecondAction: false,
                withTertiaryAction: false,
            },
            pointerEvents: 'auto',
        },
        signUp: {
            category: '',
            actorName: '',
            transparentBackground: false,
            withBottomStroke: true,
            withHeaderActions: true,
            withHeaderLeft: true,
            withHeaderRight: false,
            headerRightOptions: {
                withFirstAction: false,
                withSecondAction: false,
                withTertiaryAction: false,
            },
            pointerEvents: 'auto',
        },
        resetPassword: {
            category: '',
            actorName: '',
            transparentBackground: false,
            withBottomStroke: true,
            withHeaderActions: true,
            withHeaderLeft: true,
            withHeaderRight: false,
            headerRightOptions: {
                withFirstAction: false,
                withSecondAction: false,
                withTertiaryAction: false,
            },
            pointerEvents: 'auto',
        },
        home: {
            category: '',
            actorName: '',
            transparentBackground: true,
            withBottomStroke: false,
            withHeaderActions: true,
            withHeaderLeft: false,
            withHeaderRight: true,
            headerRightOptions: {
                withFirstAction: true,
                withSecondAction: true,
                withTertiaryAction: true,
            },
            pointerEvents: 'auto',
        },
        categories: {
            category: 'Categorias',
            actorName: '',
            transparentBackground: false,
            withBottomStroke: true,
            withHeaderActions: true,
            withHeaderLeft: false,
            withHeaderRight: true,
            headerRightOptions: {
                withFirstAction: true,
                withSecondAction: true,
                withTertiaryAction: true,
            },
            pointerEvents: 'auto',
        },
        me: {
            category: 'Eu',
            actorName: '',
            transparentBackground: false,
            withBottomStroke: true,
            withHeaderActions: true,
            withHeaderLeft: false,
            withHeaderRight: true,
            headerRightOptions: {
                withFirstAction: true,
                withSecondAction: true,
                withTertiaryAction: true,
            },
            pointerEvents: 'auto',
        },
        search: {
            category: '',
            actorName: '',
            transparentBackground: false,
            withBottomStroke: false,
            withHeaderActions: true,
            withHeaderLeft: true,
            withHeaderRight: true,
            headerRightOptions: {
                withFirstAction: true,
                withSecondAction: true,
                withTertiaryAction: false,
            },
            pointerEvents: 'auto',
        },
        explorer: {
            category: params.category,
            actorName: params?.actorName,
            transparentBackground: false,
            withBottomStroke: true,
            withHeaderActions: true,
            withHeaderLeft: true,
            withHeaderRight: true,
            headerRightOptions: {
                withFirstAction: true,
                withSecondAction: true,
                withTertiaryAction: true,
            },
            pointerEvents: 'auto',
        },
        details: {
            category: '',
            actorName: '',
            transparentBackground: false,
            withBottomStroke: false,
            withHeaderActions: true,
            withHeaderLeft: true,
            withHeaderRight: true,
            headerRightOptions: {
                withFirstAction: true,
                withSecondAction: true,
                withTertiaryAction: true,
            },
            pointerEvents: 'auto',
        },
        actorDetails: {
            category: params?.actorName,
            actorName: '',
            transparentBackground: false,
            withBottomStroke: false,
            withHeaderActions: true,
            withHeaderLeft: true,
            withHeaderRight: true,
            headerRightOptions: {
                withFirstAction: true,
                withSecondAction: true,
                withTertiaryAction: true,
            },
            pointerEvents: 'auto',
        },
        moviesYouLiked: {
            category: 'Você curtiu',
            actorName: '',
            transparentBackground: false,
            withBottomStroke: true,
            withHeaderActions: true,
            withHeaderLeft: true,
            withHeaderRight: true,
            headerRightOptions: {
                withFirstAction: true,
                withSecondAction: true,
                withTertiaryAction: true,
            },
            pointerEvents: 'auto',
        },
        myList: {
            category: 'Minha lista',
            actorName: '',
            transparentBackground: false,
            withBottomStroke: true,
            withHeaderActions: true,
            withHeaderLeft: true,
            withHeaderRight: true,
            headerRightOptions: {
                withFirstAction: true,
                withSecondAction: true,
                withTertiaryAction: true,
            },
            pointerEvents: 'auto',
        },
        account: {
            category: 'Conta',
            actorName: '',
            transparentBackground: false,
            withBottomStroke: false,
            withHeaderActions: true,
            withHeaderLeft: true,
            withHeaderRight: false,
            headerRightOptions: {
                withFirstAction: false,
                withSecondAction: false,
                withTertiaryAction: false,
            },
            pointerEvents: 'auto',
        },
        passwordChange: {
            category: 'Alterar senha',
            actorName: '',
            transparentBackground: false,
            withBottomStroke: false,
            withHeaderActions: true,
            withHeaderLeft: true,
            withHeaderRight: false,
            headerRightOptions: {
                withFirstAction: false,
                withSecondAction: false,
                withTertiaryAction: false,
            },
            pointerEvents: 'auto',
        },
        deleteUser: {
            category: 'Excluir conta',
            actorName: '',
            transparentBackground: false,
            withBottomStroke: false,
            withHeaderActions: true,
            withHeaderLeft: true,
            withHeaderRight: false,
            headerRightOptions: {
                withFirstAction: false,
                withSecondAction: false,
                withTertiaryAction: false,
            },
            pointerEvents: 'auto',
        },
        emailChange: {
            category: 'Alterar o e-mail da conta',
            actorName: '',
            transparentBackground: false,
            withBottomStroke: false,
            withHeaderActions: true,
            withHeaderLeft: true,
            withHeaderRight: false,
            headerRightOptions: {
                withFirstAction: false,
                withSecondAction: false,
                withTertiaryAction: false,
            },
            pointerEvents: 'auto',
        },
    });

    return {
        category,
        actorName,
        transparentBackground,
        withBottomStroke,
        withHeaderActions,
        withHeaderLeft,
        withHeaderRight,
        headerRightOptions,
        pointerEvents,
    };
};
