import { HeaderGlobalSearchParams } from "../components/Header/types";
import { setHeaderOptions } from "./setHeaderOptions";

interface GetHeaderOptionsProps {
    headerGlobalSearchParams: HeaderGlobalSearchParams;
};

export function getHeaderOptions({ headerGlobalSearchParams }: GetHeaderOptionsProps) {
    const {
        title,
        transparentBackground,
        withBottomStroke,
        withHeaderLeft,
        withHeaderRight,
        headerRightOptions,
        pointerEvents,
    } = setHeaderOptions({
        signIn: {
            title: '',
            transparentBackground: false,
            withBottomStroke: false,
            withHeaderLeft: false,
            withHeaderRight: false,
            headerRightOptions: {
                withFirstAction: false,
                withSecondAction: false,
                withTertiaryAction: false,
            },
            pointerEvents: 'auto',
        },
        signUp: {
            title: '',
            transparentBackground: false,
            withBottomStroke: true,
            withHeaderLeft: true,
            withHeaderRight: false,
            headerRightOptions: {
                withFirstAction: false,
                withSecondAction: false,
                withTertiaryAction: false,
            },
            pointerEvents: 'auto',
        },
        resetPassword: {
            title: '',
            transparentBackground: false,
            withBottomStroke: true,
            withHeaderLeft: true,
            withHeaderRight: false,
            headerRightOptions: {
                withFirstAction: false,
                withSecondAction: false,
                withTertiaryAction: false,
            },
            pointerEvents: 'auto',
        },
        home: {
            title: '',
            transparentBackground: true,
            withBottomStroke: false,
            withHeaderLeft: false,
            withHeaderRight: true,
            headerRightOptions: {
                withFirstAction: true,
                withSecondAction: true,
                withTertiaryAction: true,
            },
            pointerEvents: 'auto',
        },
        categories: {
            title: 'Categorias',
            transparentBackground: false,
            withBottomStroke: true,
            withHeaderLeft: false,
            withHeaderRight: true,
            headerRightOptions: {
                withFirstAction: true,
                withSecondAction: true,
                withTertiaryAction: true,
            },
            pointerEvents: 'auto',
        },
        me: {
            title: 'Eu',
            transparentBackground: false,
            withBottomStroke: true,
            withHeaderLeft: false,
            withHeaderRight: true,
            headerRightOptions: {
                withFirstAction: true,
                withSecondAction: true,
                withTertiaryAction: true,
            },
            pointerEvents: 'auto',
        },
        search: {
            title: '',
            transparentBackground: false,
            withBottomStroke: false,
            withHeaderLeft: true,
            withHeaderRight: true,
            headerRightOptions: {
                withFirstAction: true,
                withSecondAction: true,
                withTertiaryAction: false,
            },
            pointerEvents: 'auto',
        },
        explorer: {
            title: headerGlobalSearchParams.title,
            transparentBackground: false,
            withBottomStroke: true,
            withHeaderLeft: true,
            withHeaderRight: true,
            headerRightOptions: {
                withFirstAction: true,
                withSecondAction: true,
                withTertiaryAction: true,
            },
            pointerEvents: 'auto',
        },
        similarContentExplorer: {
            title: 'Conteúdos similares',
            transparentBackground: false,
            withBottomStroke: true,
            withHeaderLeft: true,
            withHeaderRight: true,
            headerRightOptions: {
                withFirstAction: true,
                withSecondAction: true,
                withTertiaryAction: true,
            },
            pointerEvents: 'auto',
        },
        actorExplorer: {
            title: headerGlobalSearchParams.title,
            transparentBackground: false,
            withBottomStroke: true,
            withHeaderLeft: true,
            withHeaderRight: true,
            headerRightOptions: {
                withFirstAction: true,
                withSecondAction: true,
                withTertiaryAction: true,
            },
            pointerEvents: 'auto',
        },
        details: {
            title: '',
            transparentBackground: false,
            withBottomStroke: false,
            withHeaderLeft: true,
            withHeaderRight: true,
            headerRightOptions: {
                withFirstAction: true,
                withSecondAction: true,
                withTertiaryAction: true,
            },
            pointerEvents: 'auto',
        },
        actorDetails: {
            title: headerGlobalSearchParams?.actorName,
            transparentBackground: false,
            withBottomStroke: false,
            withHeaderLeft: true,
            withHeaderRight: true,
            headerRightOptions: {
                withFirstAction: true,
                withSecondAction: true,
                withTertiaryAction: true,
            },
            pointerEvents: 'auto',
        },
        moviesYouLiked: {
            title: 'Você curtiu',
            transparentBackground: false,
            withBottomStroke: true,
            withHeaderLeft: true,
            withHeaderRight: true,
            headerRightOptions: {
                withFirstAction: true,
                withSecondAction: true,
                withTertiaryAction: true,
            },
            pointerEvents: 'auto',
        },
        myList: {
            title: 'Minha lista',
            transparentBackground: false,
            withBottomStroke: true,
            withHeaderLeft: true,
            withHeaderRight: true,
            headerRightOptions: {
                withFirstAction: true,
                withSecondAction: true,
                withTertiaryAction: true,
            },
            pointerEvents: 'auto',
        },
        account: {
            title: 'Conta',
            transparentBackground: false,
            withBottomStroke: false,
            withHeaderLeft: true,
            withHeaderRight: false,
            headerRightOptions: {
                withFirstAction: false,
                withSecondAction: false,
                withTertiaryAction: false,
            },
            pointerEvents: 'auto',
        },
        passwordChange: {
            title: 'Alterar senha',
            transparentBackground: false,
            withBottomStroke: false,
            withHeaderLeft: true,
            withHeaderRight: false,
            headerRightOptions: {
                withFirstAction: false,
                withSecondAction: false,
                withTertiaryAction: false,
            },
            pointerEvents: 'auto',
        },
        deleteUser: {
            title: 'Excluir conta',
            transparentBackground: false,
            withBottomStroke: false,
            withHeaderLeft: true,
            withHeaderRight: false,
            headerRightOptions: {
                withFirstAction: false,
                withSecondAction: false,
                withTertiaryAction: false,
            },
            pointerEvents: 'auto',
        },
        emailChange: {
            title: 'Alterar o e-mail da conta',
            transparentBackground: false,
            withBottomStroke: false,
            withHeaderLeft: true,
            withHeaderRight: false,
            headerRightOptions: {
                withFirstAction: false,
                withSecondAction: false,
                withTertiaryAction: false,
            },
            pointerEvents: 'auto',
        },
        usernameChange: {
            title: 'Alterar usuário',
            transparentBackground: false,
            withBottomStroke: false,
            withHeaderLeft: true,
            withHeaderRight: false,
            headerRightOptions: {
                withFirstAction: false,
                withSecondAction: false,
                withTertiaryAction: false,
            },
            pointerEvents: 'auto',
        },
    });

    return {
        title,
        transparentBackground,
        withBottomStroke,
        withHeaderLeft,
        withHeaderRight,
        headerRightOptions,
        pointerEvents,
    };
};
